import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from '@/components/Navbar';

const geistSans = localFont({
  src: "../app/fonts/Satoshi-Black.woff", // Removed the extra slash
  variable: "--font-geist-sans",
  weight: "100 900 200 400 500",
});
const geistMono = localFont({
  src: "./fonts/Satoshi-Light.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const regular = localFont({
  src: "./fonts/Satoshi-Regular.woff",
  variable: "--font-geist-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable} ${regular.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
